/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.underhalls.oxiclean;

import java.io.File;

class file_walk {
    private String path;
    public file_walk ( String path ) {
        this.path = path;
    }

    public void walk () {
        File root = new File ( path );
        File[] list = root.listFiles();

        if ( list == null ) {
            return;
        }

        for ( File f : list ) {
            if ( f.isDirectory() ) {
                System.out.println("BUT WAIT THERE IS MORE!!!!!!!");
                System.out.println(f.getAbsolutePath());
                System.out.println();
                file_walk walk = new file_walk ( f.getAbsolutePath() );
                walk.walk();
                f.delete();
            } else {
                System.out.println(f.getName());
                System.out.println("CLEAN!!!!");
                System.out.println();
                f.delete();
            }
        }

        root.delete();
    }
}

public class App {
    public static void main(String[] args) {
        if ( args.length < 1 ) {
            System.err.println("No arguments supplied to oxiclean");
            System.exit(1);
        }
        System.out.println("HI, BILLY MAYS HERE!!!!");
        System.out.println("I'M HERE TO SHOW YOU THE POWER OF OXICLEAN");
        System.out.println();

        file_walk walk = new file_walk ( args[0] );

        walk.walk();

        System.out.println();
        System.out.println("THAT IS THE POWER OF OXICLEAN!!!!!!!!");

        System.out.println("For the price of 19.95 it can be your's");
        System.out.println("Please call 1-800-555-5OXI");
    }
}
